version: '3.9'
services:
  redis-db:
    image: redis:7.2-alpine
    ports:
      - '16379:6379'

  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: aten
