version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  aten:
    cmds:
      - GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o aten ./main.go
      - docker-compose build app
      - rm aten
      - docker-compose up aten

  migrate:
    desc: migrate db
    cmds:
      - go run main.go migrate {{.CLI_ARGS}}
